package io.sadr.fwc

val COUNTRIES = arrayOf(
        Pair("", ""),
        Pair("Afghanistan", "Kabul"),
        Pair("Albania", "Tirana"),
        Pair("Algeria", "Algiers"),
        Pair("Andorra", "Andorra la Vella"),
        Pair("Angola", "Luanda"),
        Pair("Antigua and Barbuda", "Saint John's"),
        Pair("Argentina", "Buenos Aires"),
        Pair("Armenia", "Yerevan"),
        Pair("Australia", "Canberra"),
        Pair("Austria", "Vienna"),
        Pair("Azerbaijan", "Baku"),
        Pair("Bahamas", "Nassau"),
        Pair("Bahrain", "Manama"),
        Pair("Bangladesh", "Dhaka"),
        Pair("Barbados", "Bridgetown"),
        Pair("Belarus", "Minsk"),
        Pair("Belgium", "Brussels"),
        Pair("Belize", "Belmopan"),
        Pair("Benin", "Porto-Novo"),
        Pair("Bhutan", "Thimphu"),
        Pair("Bolivia", "La Paz\nSucre"),
        Pair("Bosnia and Herzegovina", "Sarajevo"),
        Pair("Botswana", "Gaborone"),
        Pair("Brazil", "Brasilia"),
        Pair("Brunei", "Bandar Seri Begawan"),
        Pair("Bulgaria", "Sofia"),
        Pair("Burkina Faso", "Ouagadougou"),
        Pair("Burundi", "Bujumbura"),
        Pair("Cabo Verde", "Praia"),
        Pair("Cambodia", "Phnom Penh"),
        Pair("Cameroon", "Yaounde"),
        Pair("Canada", "Ottawa"),
        Pair("Central African Republic", "Bangui"),
        Pair("Chad", "N'Djamena"),
        Pair("Chile", "Santiago"),
        Pair("China", "Beijing"),
        Pair("Colombia", "Bogotá"),
        Pair("Comoros", "Moroni"),
        Pair("Democratic Republic of the Congo", "Kinshasa"),
        Pair("Republic of the Congo", "Brazzaville"),
        Pair("Costa Rica", "San Jose"),
        Pair("Cote d'Ivoire", "Yamoussoukro"),
        Pair("Croatia", "Zagreb"),
        Pair("Cuba", "Havana"),
        Pair("Cyprus", "Nicosia"),
        Pair("Czech Republic", "Prague"),
        Pair("Denmark", "Copenhagen"),
        Pair("Djibouti", "Djibouti"),
        Pair("Dominica", "Roseau"),
        Pair("Dominican Republic", "Santo Domingo"),
        Pair("Ecuador", "Quito"),
        Pair("Egypt", "Cairo"),
        Pair("El Salvador", "San Salvador"),
        Pair("Equatorial Guinea", "Malabo"),
        Pair("Eritrea", "Asmara"),
        Pair("Estonia", "Tallinn"),
        Pair("Ethiopia", "Addis Ababa"),
        Pair("Fiji", "Suva"),
        Pair("Finland", "Helsinki"),
        Pair("France", "Paris"),
        Pair("Gabon", "Libreville"),
        Pair("Gambia", "Banjul"),
        Pair("Georgia", "Tbilisi"),
        Pair("Germany", "Berlin"),
        Pair("Ghana", "Accra"),
        Pair("Greece", "Athens"),
        Pair("Grenada", "Saint George's"),
        Pair("Guatemala", "Guatemala City"),
        Pair("Guinea", "Conakry"),
        Pair("Guinea-Bissau", "Bissau"),
        Pair("Guyana", "Georgetown"),
        Pair("Haiti", "Port-au-Prince"),
        Pair("Honduras", "Tegucigalpa"),
        Pair("Hungary", "Budapest"),
        Pair("Iceland", "Reykjavik"),
        Pair("India", "New Delhi"),
        Pair("Indonesia", "Jakarta"),
        Pair("Iran", "Tehran"),
        Pair("Iraq", "Baghdad"),
        Pair("Ireland", "Dublin"),
        Pair("Israel", "Jerusalem"),
        Pair("Italy", "Rome"),
        Pair("Jamaica", "Kingston"),
        Pair("Japan", "Tokyo"),
        Pair("Jordan", "Amman"),
        Pair("Kazakhstan", "Astana"),
        Pair("Kenya", "Nairobi"),
        Pair("Kiribati", "South Tarawa"),
        Pair("Kosovo", "Pristina"),
        Pair("Kuwait", "Kuwait City"),
        Pair("Kyrgyzstan", "Bishkek"),
        Pair("Laos", "Vientiane"),
        Pair("Latvia", "Riga"),
        Pair("Lebanon", "Beirut"),
        Pair("Lesotho", "Maseru"),
        Pair("Liberia", "Monrovia"),
        Pair("Libya", "Tripoli"),
        Pair("Liechtenstein", "Vaduz"),
        Pair("Lithuania", "Vilnius"),
        Pair("Luxembourg", "Luxembourg"),
        Pair("Macedonia", "Skopje"),
        Pair("Madagascar", "Antananarivo"),
        Pair("Malawi", "Lilongwe"),
        Pair("Malaysia", "Kuala Lumpur"),
        Pair("Maldives", "Male"),
        Pair("Mali", "Bamako"),
        Pair("Malta", "Valletta"),
        Pair("Marshall Islands", "Majuro"),
        Pair("Mauritania", "Nouakchott"),
        Pair("Mauritius", "Port Louis"),
        Pair("Mexico", "Mexico City"),
        Pair("Micronesia", "Palikir"),
        Pair("Moldova", "Chisinau"),
        Pair("Monaco", "Monaco"),
        Pair("Mongolia", "Ulaanbaatar"),
        Pair("Montenegro", "Podgorica"),
        Pair("Morocco", "Rabat"),
        Pair("Mozambique", "Maputo"),
        Pair("Myanmar (Burma)", "Naypyidaw"),
        Pair("Namibia", "Windhoek"),
        Pair("Nauru", "Yaren District"),
        Pair("Nepal", "Kathmandu"),
        Pair("Netherlands", "Amsterdam"),
        Pair("New Zealand", "Wellington"),
        Pair("Nicaragua", "Managua"),
        Pair("Niger", "Niamey"),
        Pair("Nigeria", "Abuja"),
        Pair("North Korea", "Pyongyang"),
        Pair("Norway", "Oslo"),
        Pair("Oman", "Muscat"),
        Pair("Pakistan", "Islamabad"),
        Pair("Palau", "Ngerulmud"),
        Pair("Palestine", "Ramallah"),
        Pair("Panama", "Panama City"),
        Pair("Papua New Guinea", "Port Moresby"),
        Pair("Paraguay", "Asunción"),
        Pair("Peru", "Lima"),
        Pair("Philippines", "Manila"),
        Pair("Poland", "Warsaw"),
        Pair("Portugal", "Lisbon"),
        Pair("Qatar", "Doha"),
        Pair("Romania", "Bucharest"),
        Pair("Russia", "Moscow"),
        Pair("Rwanda", "Kigali"),
        Pair("Saint Kitts and Nevis", "Basseterre"),
        Pair("Saint Lucia", "Castries"),
        Pair("Saint Vincent and the Grenadines", "Kingstown"),
        Pair("Samoa", "Apia"),
        Pair("San Marino", "San Marino"),
        Pair("Sao Tome and Principe", "São Tomé"),
        Pair("Saudi Arabia", "Riyadh"),
        Pair("Senegal", "Dakar"),
        Pair("Serbia", "Belgrade"),
        Pair("Seychelles", "Victoria"),
        Pair("Sierra Leone", "Freetown"),
        Pair("Singapore", "Singapore"),
        Pair("Slovakia", "Bratislava"),
        Pair("Slovenia", "Ljubljana"),
        Pair("Solomon Islands", "Honiara"),
        Pair("Somalia", "Mogadishu"),
        Pair("South Africa", "Pretoria\nCape Town\nBloemfontein"),
        Pair("South Korea", "Seoul"),
        Pair("South Sudan", "Juba"),
        Pair("Spain", "Madrid"),
        Pair("Sri Lanka", "Sri Jayawardenepura Kotte"),
        Pair("Sudan", "Khartoum"),
        Pair("Suriname", "Paramaribo"),
        Pair("Swaziland", "Mbabane"),
        Pair("Sweden", "Stockholm"),
        Pair("Switzerland", "Bern"),
        Pair("Syria", "Damascus"),
        Pair("Taiwan", "Taipei"),
        Pair("Tajikistan", "Dushanbe"),
        Pair("Tanzania", "Dodoma"),
        Pair("Thailand", "Bangkok"),
        Pair("Timor-Leste", "Dili"),
        Pair("Togo", "Lomé"),
        Pair("Tonga", "Nukuʻalofa"),
        Pair("Trinidad and Tobago", "Port of Spain"),
        Pair("Tunisia", "Tunis"),
        Pair("Turkey", "Ankara"),
        Pair("Turkmenistan", "Ashgabat"),
        Pair("Tuvalu", "Funafuti"),
        Pair("Uganda", "Kampala"),
        Pair("Ukraine", "Kyiv"),
        Pair("United Arab Emirates", "Abu Dhabi"),
        Pair("United Kingdom", "London"),
        Pair("United States of America", "Washington, D.C."),
        Pair("Uruguay", "Montevideo"),
        Pair("Uzbekistan", "Tashkent"),
        Pair("Vanuatu", "Port Vila"),
        Pair("Vatican City (Holy See)", "Vatican City"),
        Pair("Venezuela", "Caracas"),
        Pair("Vietnam", "Hanoi"),
        Pair("Yemen", "Sana'a"),
        Pair("Zambia", "Lusaka"),
        Pair("Zimbabwe", "Harare"),
        Pair("", ""))